import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs';
import {loadRegistry,hostAllowed,normalizeTarget,buildInvocation,classifyGate,verifyPostCondition,validateAction} from '../tools/osa-browser-runtime.mjs';
test('registry valid and initially unverified',async()=>{const r=await loadRegistry();assert.ok(Object.keys(r.sites).length>=6);for(const s of Object.values(r.sites))assert.equal(s.authEvidence.configured,false);});
test('domain guard',async()=>{const s=(await loadRegistry()).sites.linkedin;assert.equal(hostAllowed('www.linkedin.com',s.domains),true);assert.equal(hostAllowed('linkedin.com.example.org',s.domains),false);assert.doesNotThrow(()=>normalizeTarget(s,'https://www.linkedin.com/login'));assert.throws(()=>normalizeTarget(s,'https://example.org/'));assert.throws(()=>normalizeTarget(s,'http://linkedin.com/'));});
test('persistent profile invocation',async()=>{const s=(await loadRegistry()).sites.laborx,a=buildInvocation(s,'open',['https://laborx.com/'],{profileRoot:'/tmp/p'});assert.deepEqual(a.slice(0,5),['--session','osa-laborx','--profile','/tmp/p/laborx','--pin-tab']);assert.ok(a.includes('--content-boundaries'));});
test('action allowlist',()=>{assert.equal(validateAction('click',['@e1']),true);assert.equal(validateAction('auth',['login','laborx']),true);assert.throws(()=>validateAction('shell',['id']));assert.throws(()=>validateAction('auth',['save','x']));});
test('gates',()=>{assert.equal(classifyGate({status:403}),'security_gate');assert.equal(classifyGate({text:'Enter the verification code'}),'verification_gate');assert.equal(classifyGate({text:'Verify your identity with passport'}),'identity_gate');assert.equal(classifyGate({text:'Accept the terms and agreement'}),'binding_gate');assert.equal(classifyGate({text:'Dashboard'}),'none');});
test('auth requires verified postconditions',async()=>{const r=await loadRegistry();assert.equal(verifyPostCondition(r.sites.laborx,{url:'https://laborx.com/dashboard',text:'Welcome'}).verified,false);const s={...r.sites.laborx,authEvidence:{configured:true,urlIncludes:['/dashboard'],requiredText:['Welcome'],absentText:['Sign in']}};assert.equal(verifyPostCondition(s,{url:'https://laborx.com/dashboard',text:'Welcome Omar'}).verified,true);assert.equal(verifyPostCondition(s,{url:'https://laborx.com/dashboard',text:'Welcome Sign in'}).verified,false);});
test('installer pins version and protects env',()=>{const s=fs.readFileSync('ops/install-browser-runtime.sh','utf8');assert.match(s,/VERSION="0\.35\.1"/);assert.match(s,/chmod 0600 \/etc\/osa\/browser-runtime\.env/);assert.match(s,/openssl rand -hex 32/);});
