import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const sb=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
const BASE="https://pkctqxeydfuiupadaoov.supabase.co/functions/v1/osa-pilot-usdc";
const PAY_TO="0xCc34D733F5f387d0128021E636D023472CB5df0c";
const TRANSFER_TOPIC="0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef";
const networks:any={
  base:{label:"Base",chainId:8453,rpc:"https://mainnet.base.org",usdc:"0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"},
  polygon:{label:"Polygon",chainId:137,rpc:"https://polygon-rpc.com",usdc:"0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359"},
  arbitrum:{label:"Arbitrum",chainId:42161,rpc:"https://arb1.arbitrum.io/rpc",usdc:"0xaf88d065e77c8cC2239327C5EDb3A432268e5831"}
};
const H={"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*","access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"content-type"};
const json=(b:any,s=200)=>Response.json(b,{status:s,headers:H});
function emailOk(v:string){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)&&v.length<=320;}
function uuidOk(v:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);}
function randInt(max:number){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%max;}
function paymentUri(network:string,units:number){const n=networks[network];return `ethereum:${n.usdc}@${n.chainId}/transfer?address=${PAY_TO}&uint256=${units}`;}
async function rpc(url:string,method:string,params:any[]){const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:1,method,params}),signal:AbortSignal.timeout(15000)});const j=await r.json();if(!r.ok||j.error)throw new Error(j?.error?.message||`rpc_${r.status}`);return j.result;}
async function verifyEvm(order:any,tx:string){const n=networks[order.network];if(!n)return{ok:false,reason:"unsupported_network"};const receipt=await rpc(n.rpc,"eth_getTransactionReceipt",[tx]);if(!receipt)return{ok:false,pending:true,reason:"transaction_not_found"};if(receipt.status!=="0x1")return{ok:false,reason:"transaction_failed"};const blockHex=await rpc(n.rpc,"eth_blockNumber",[]);const conf=Number(BigInt(blockHex)-BigInt(receipt.blockNumber)+1n);let matched=0n;for(const l of receipt.logs||[]){if(String(l.address).toLowerCase()!==n.usdc.toLowerCase())continue;if(String(l.topics?.[0]||"").toLowerCase()!==TRANSFER_TOPIC)continue;const to="0x"+String(l.topics?.[2]||"").slice(-40);if(to.toLowerCase()!==PAY_TO.toLowerCase())continue;try{matched+=BigInt(l.data)}catch{}}if(matched<BigInt(order.amount_units))return{ok:false,reason:"required_usdc_transfer_not_found",received_units:matched.toString(),confirmations:conf};if(conf<2)return{ok:false,pending:true,reason:"waiting_confirmations",received_units:matched.toString(),confirmations:conf};return{ok:true,received_units:matched.toString(),confirmations:conf,block_number:Number(BigInt(receipt.blockNumber))};}
async function subscriptionFor(orderId:string){const{data}=await sb.from("osa_pilot_subscriptions").select("id,status,opportunity_id,server_id,endpoint,started_at,ends_at").eq("order_id",orderId).maybeSingle();return data||null;}
async function createOrder(body:any){const email=String(body.email||"").trim().toLowerCase(),network=String(body.network||"").toLowerCase(),opportunityId=String(body.opportunity_id||"").trim();if(!emailOk(email))return json({ok:false,error:"invalid_email"},400);if(!networks[network])return json({ok:false,error:"unsupported_network",supported_networks:Object.keys(networks)},400);if(opportunityId&&!uuidOk(opportunityId))return json({ok:false,error:"invalid_opportunity_id"},400);if(opportunityId){const{data:opp}=await sb.from("opportunities").select("id,endpoint").eq("id",opportunityId).maybeSingle();if(!opp?.id||!opp.endpoint)return json({ok:false,error:"opportunity_not_found"},404);}await sb.from("osa_crypto_orders").update({status:"expired"}).eq("status","pending").eq("sku","pilot-30d").lt("expires_at",new Date().toISOString());const since=new Date(Date.now()-3600000).toISOString();const{count}=await sb.from("osa_crypto_orders").select("id",{count:"exact",head:true}).eq("email",email).eq("sku","pilot-30d").gte("created_at",since);if((count||0)>=5)return json({ok:false,error:"too_many_pending_orders"},429);for(let i=0;i<20;i++){const units=79_000_000+1+randInt(9999);const n=networks[network];const evidence:any={asset:"USDC",network_label:n.label,product:"30-Day MCP Reliability Pilot",base_price_usd:79};if(opportunityId){evidence.opportunity_id=opportunityId;evidence.attribution="incident_checkout_query";}const{data,error}=await sb.from("osa_crypto_orders").insert({email,sku:"pilot-30d",credits:1,network,amount_units:units,amount_usd:units/1e6,pay_to:PAY_TO,status:"pending",expires_at:new Date(Date.now()+30*60000).toISOString(),evidence}).select("id,email,sku,network,amount_units,amount_usd,pay_to,status,expires_at,evidence").single();if(!error)return json({ok:true,order:data,asset:"USDC",decimals:6,product:"30-Day MCP Reliability Pilot",base_price_usd:79,payment_uri:paymentUri(network,units),instructions:`Send exactly ${(units/1e6).toFixed(6)} USDC on ${n.label}, then submit the transaction hash.`});if(error.code!=="23505")return json({ok:false,error:"order_create_failed"},500);}return json({ok:false,error:"amount_allocation_busy"},503);}
async function paymentTruth(tx:string){const{data}=await sb.from("payment_events").select("event_type,payment_id,credits_delta,status,occurred_at").eq("provider","direct_usdc").eq("payment_id",tx).gt("credits_delta",0).in("status",["fulfilled","pending_claim"]).order("created_at",{ascending:false}).limit(1).maybeSingle();return data||null;}
async function verifiedResponse(order:any,tx:string,status="verified"){const truth=await paymentTruth(tx);const subscription=await subscriptionFor(String(order.id));return json({ok:true,status,order_id:order.id,network:order.network,tx_hash:tx,product:"30-Day MCP Reliability Pilot",amount_usd:Number(order.amount_usd),payment_truth:truth,fulfillment_status:subscription?.status==="active"?"active_30_day_monitoring":"payment_verified_target_needed",subscription:subscription?{status:subscription.status,endpoint:subscription.endpoint,started_at:subscription.started_at,ends_at:subscription.ends_at,opportunity_id:subscription.opportunity_id}:null,truth:"Verified on-chain USDC payment evidence. Payout is tracked separately."});}
async function verifyOrder(body:any){const id=String(body.order_id||""),tx=String(body.tx_hash||"").trim();if(!/^[0-9a-f-]{36}$/i.test(id))return json({ok:false,error:"invalid_order_id"},400);if(!/^0x[0-9a-fA-F]{64}$/.test(tx))return json({ok:false,error:"invalid_tx_hash"},400);const{data:order}=await sb.from("osa_crypto_orders").select("*").eq("id",id).eq("sku","pilot-30d").maybeSingle();if(!order)return json({ok:false,error:"order_not_found"},404);if(order.status==="verified")return await verifiedResponse(order,String(order.tx_hash||tx),"already_verified");if(order.status!=="pending")return json({ok:false,error:`order_${order.status}`},409);if(new Date(order.expires_at).getTime()<Date.now()){await sb.from("osa_crypto_orders").update({status:"expired"}).eq("id",id);return json({ok:false,error:"order_expired"},410);}if(!networks[order.network])return json({ok:false,error:"order_network_not_supported"},409);const{data:used}=await sb.from("osa_crypto_orders").select("id").eq("network",order.network).eq("tx_hash",tx).neq("id",id).maybeSingle();if(used)return json({ok:false,error:"transaction_already_used"},409);let evidence:any;try{evidence=await verifyEvm(order,tx);}catch(e){return json({ok:false,error:"rpc_unavailable",detail:String((e as Error).message).slice(0,160)},503);}if(!evidence.ok){if(evidence.pending)return json({ok:false,status:"pending",...evidence},202);return json({ok:false,status:"not_verified",...evidence},400);}const merged={...(order.evidence||{}),verification:evidence,receipt_recorded:true};const verifiedAt=new Date().toISOString();const{error}=await sb.from("osa_crypto_orders").update({status:"verified",tx_hash:tx,verified_at:verifiedAt,evidence:merged}).eq("id",id).eq("status","pending");if(error)return json({ok:false,error:"verification_persist_failed"},500);const{data:fresh}=await sb.from("osa_crypto_orders").select("*").eq("id",id).single();const truth=await paymentTruth(tx);if(!truth)return json({ok:false,error:"payment_truth_sync_missing",order_id:id,tx_hash:tx},500);return await verifiedResponse(fresh||{...order,id,verified_at:verifiedAt},tx,"verified");}
const page=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OSA Pilot — USDC</title><style>body{font-family:system-ui;background:#07111f;color:#fff;max-width:760px;margin:auto;padding:24px}input,select,button{width:100%;padding:13px;margin:7px 0;border-radius:10px;border:1px solid #35506a;box-sizing:border-box;background:#0d1b2d;color:#fff}button,a.wallet{background:#63e6aa;color:#042015;font-weight:800}a.wallet{display:none;text-align:center;text-decoration:none;padding:13px;margin:7px 0;border-radius:10px}.card{background:#0e1d2e;padding:20px;border-radius:16px;margin-top:16px}.muted{color:#9fb3c7;line-height:1.5}code,pre{white-space:pre-wrap;word-break:break-all}.ok{color:#91f5bf}</style></head><body><h1>30-Day MCP Reliability Pilot</h1><p class="muted">Pay $79 in USDC from any wallet on Base, Polygon, or Arbitrum. OSA issues a unique exact amount and verifies it on-chain.</p><p class="muted">Compatible with Coinbase Wallet, MetaMask, Trust Wallet, Binance Wallet, and other wallets that handle ERC-681 requests.</p><div class="card"><input id="email" type="email" placeholder="Email"><select id="network"><option value="base">Base</option><option value="polygon">Polygon</option><option value="arbitrum">Arbitrum</option></select><button onclick="createOrder()">Create $79 payment</button><div id="order"></div><a id="walletLink" class="wallet">Open compatible wallet</a></div><div class="card"><input id="oid" placeholder="Order ID"><input id="tx" placeholder="Transaction hash"><button onclick="verifyOrder()">Verify payment</button><pre id="result"></pre></div><script>const params=new URLSearchParams(location.search),opp=params.get('opportunity_id')||'';async function createOrder(){const r=await fetch('${BASE}/order',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:email.value,network:network.value,opportunity_id:opp})});const d=await r.json();if(!d.ok){order.textContent=JSON.stringify(d);return}oid.value=d.order.id;walletLink.href=d.payment_uri;walletLink.style.display='block';order.innerHTML='<p>Send exactly <b>'+Number(d.order.amount_usd).toFixed(6)+' USDC</b></p><p>To:</p><code>'+d.order.pay_to+'</code><p>Network: '+d.order.network+'</p><p>Expires: '+d.order.expires_at+'</p>'}async function verifyOrder(){const r=await fetch('${BASE}/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({order_id:oid.value,tx_hash:tx.value})});const d=await r.json();result.textContent=JSON.stringify(d,null,2);if(d.ok&&d.fulfillment_status==='active_30_day_monitoring')result.className='ok'}</script></body></html>`;
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:H});const u=new URL(req.url),route=u.pathname.split('/').filter(Boolean).pop()||"";if(req.method==="GET"&&route==="health")return json({ok:true,service:"OSA Pilot USDC Checkout",product:"30-Day MCP Reliability Pilot",base_price_usd:79,asset:"USDC",networks:Object.keys(networks),pay_to:PAY_TO,payment_verification:"onchain",payment_uri_standard:"ERC-681",revenue_truth:"payment_events + verified osa_crypto_orders",fulfillment:"automatic_30_day_subscription_when_attributed"});if(req.method==="GET"&&(route==="osa-pilot-usdc"||route===""))return new Response(page,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff","x-frame-options":"DENY","referrer-policy":"no-referrer","content-security-policy":"default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src https://pkctqxeydfuiupadaoov.supabase.co; base-uri 'none'; frame-ancestors 'none'"}});if(req.method==="POST"&&route==="order")return await createOrder(await req.json().catch(()=>({})));if(req.method==="POST"&&route==="verify")return await verifyOrder(await req.json().catch(()=>({})));return json({ok:false,error:"not_found"},404);});
