create extension if not exists pg_cron with schema pg_catalog;

create table if not exists private.osa_research_watch_sources (
  id bigint generated by default as identity primary key,
  url text not null unique check (url ~ '^https://'),
  label text not null check (char_length(label) between 2 and 120),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

revoke all on private.osa_research_watch_sources from public, anon, authenticated, service_role;

insert into private.osa_research_watch_sources(id, label, url) values
  (1, 'storybook issue 12641', 'https://github.com/storybookjs/storybook/issues/12641'),
  (2, 'typeorm issue 3357', 'https://github.com/typeorm/typeorm/issues/3357'),
  (3, 'google go-github', 'https://github.com/google/go-github'),
  (4, 'strapi', 'https://github.com/strapi/strapi'),
  (5, 'autokey issue 87', 'https://github.com/autokey/autokey/issues/87'),
  (6, 'zed', 'https://github.com/zed-industries/zed'),
  (7, 'deno', 'https://github.com/denoland/deno'),
  (8, 'algora tv issue 130', 'https://github.com/algora-io/tv/issues/130'),
  (9, 'keycloak', 'https://github.com/keycloak/keycloak'),
  (10, 'formbricks', 'https://github.com/formbricks/formbricks'),
  (11, 'tooljet', 'https://github.com/ToolJet/ToolJet'),
  (12, 'qtop', 'https://github.com/qtop/qtop'),
  (13, 'electron', 'https://github.com/electron/electron'),
  (14, 'trovu', 'https://github.com/trovu/trovu'),
  (15, 'algora tscircuit bounties', 'https://algora.io/tscircuit/bounties'),
  (16, 'algora algora bounties', 'https://algora.io/algora/bounties'),
  (17, 'superteam earn', 'https://earn.superteam.fun'),
  (18, 'github open bounty search', 'https://github.com/search?q=is%3Aissue+is%3Aopen+label%3Abounty&type=issues'),
  (19, 'opire', 'https://opire.dev/home'),
  (20, 'algora bounty api docs', 'https://api.docs.algora.io/bounties')
on conflict (id) do update set label = excluded.label, url = excluded.url, active = true;

create or replace function private.osa_enqueue_daily_opportunity_scan()
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id uuid;
  v_day date := (now() at time zone 'Asia/Riyadh')::date;
  v_query text;
  v_sources text;
begin
  select string_agg(format('%s. %s', s.id, s.url), E'\n' order by s.id)
  into v_sources
  from private.osa_research_watch_sources s
  where s.active;

  v_query := format(
    'Search as of %s for individual-accessible paid programming or AI bounties that are verifiably open now. Inspect this exact locked list without adding, removing, renaming, or replacing entries:\n%s\nFor every candidate, cross-check the reward platform against the canonical GitHub issue state and maintainer eligibility instructions. Reject closed issues, already-rewarded work, repositories without a specific funded issue, tasks that prohibit community PRs, points, testnets, airdrops, contests without a currently open task, and anything requiring upfront payment. Require the exact task title, amount and currency, deadline if one exists, requirements, official direct task URL, and evidence that work can still be claimed. If no task meets every requirement, say: No sufficiently verified task found today.',
    v_day,
    coalesce(v_sources, '(watchlist empty)')
  );

  insert into public.osa_research_jobs(query, requested_by, priority, dedupe_key, metadata)
  values (
    v_query,
    'supabase:daily-opportunity-scan',
    8,
    'paid-coding-opportunities-watchlist-v1-' || v_day::text,
    jsonb_build_object('purpose', 'daily_paid_opportunity_scan', 'local_day', v_day)
  )
  on conflict (dedupe_key) where dedupe_key is not null
  do update set updated_at = public.osa_research_jobs.updated_at
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function private.osa_enqueue_daily_opportunity_scan() from public, anon, authenticated, service_role;

do $$
declare
  v_job_id bigint;
begin
  for v_job_id in select jobid from cron.job where jobname = 'osa-daily-paid-opportunity-scan'
  loop
    perform cron.unschedule(v_job_id);
  end loop;

  perform cron.schedule(
    'osa-daily-paid-opportunity-scan',
    '0 6 * * *',
    'select private.osa_enqueue_daily_opportunity_scan()'
  );
end;
$$;
